#ifndef CNDARRAY_MULTIARRAY_NDARRAYTYPES_H_
#define CNDARRAY_MULTIARRAY_NDARRAYTYPES_H_

typedef enum {
    ARRAY_INT8,
    ARRAY_INT16,
    ARRAY_INT32,
    ARRAY_INT64,

    ARRAY_FLOAT32,
    ARRAY_FLOAT64,
} NdarrayTypes;

#endif 